package symbols

var Table = [][]interface{} {
  {"!","n!n!n!","n!"  },
  {"\\!","a ⁣ba\\!bab","a\\!b"  },
  {"#","y2\\def\\sqr#1{#1^2} \\sqr{y}y2","\\def\\sqr#1{#1^2} \\sqr{y}"  },
  {"\\#","#\\##",""  },
  {"%","","%this is a comment"  },
  {"\\%","%\\%%",""  },
  {"&","abcd\\begin{matrix} a & b\\cr c & d \\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\\\\n   c & d\n\\end{matrix}"  },
  {"\\&","&\\&&",""  },
  {"'","′'′",""  },
  {"\\'","aˊ\\text{\\'{a}}aˊ","\\text{\\'{a}}"  },
  {"(","(((",""  },
  {")",")))",""  },
  {"\\(…\\)","ab\\text{\\(\\frac a b\\)}ba​","\\text{\\(\\frac a b\\)}"  },
  {"\\","a ba\\ ba b","a\\ b"  },
  {"\\\"","a¨\\text{\\\"{a}}a¨","\\text{\\\"{a}}"  },
  {"\\$","$\\text{\\textdollar}$",""  },
  {"\\,","a  ba\\,\\,{b}ab","a\\,\\,{b}"  },
  {"\\.","a˙\\text{\\.{a}}a˙","\\text{\\.{a}}"  },
  {"\\:","a? ? ba\\:\\:{b}ab","a\\:\\:{b}"  },
  {"\\;","a?  ?  ba\\;\\;{b}ab","a\\;\\;{b}"  },
  {"_","xix_ixi​","x_i"  },
  {"\\_","_\\__",""  },
  {"\\`","aˋ\\text{\\`{a}}aˋ","\\text{\\'{a}}"  },
  {"<","<<<",""  },
  {"\\=","aˉ\\text{\\={a}}aˉ","\\text{\\={a}}"  },
  {">",">>>",""  },
  {"\\>","a? ? ba\\>\\>{b}ab","a\\>\\>{b}"  },
  {"{","{{{",""  },
  {"}","}}}",""  },
  {"{","a{a}a","{a}"  },
  {"}","a{a}a","{a}"  },
  {"\\{","${$",""  },
  {"\\}","$}$",""  },
  {"|","∣\\vert∣",""  },
  {"\\|","∥\\Vert∥",""  },
  {"~","no no no breaks\\text{no~no~no~breaks}no no no breaks","\\text{no~no~no~breaks}"  },
  {"\\~","a˜\\text{\\~{a}}a˜","\\text{\\~{a}}"  },
  {"\\\\","abcd\\begin{matrix} a & b\\\\ c & d\\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\\\\n   c & d\n\\end{matrix}"  },
  {"^","xix^ixi","x^i"  },
  {"\\^","aˆ\\text{\\^{a}}aˆ","\\text{\\^{a}}"  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\AA","A˚\\text{\\AA}A˚","\\text{\\AA}"  },
  {"\\aa","a˚\\text{\\aa}a˚","\\text{\\aa}"  },
  {"\\above","ab+1{a \\above{2pt} b+1}b+1a​","{a \\above{2pt} b+1}"  },
  {"\\abovewithdelims","Not supported",""  },
  {"\\acute","eˊ\\acute eeˊ","\\acute e"  },
  {"\\AE","Æ\\text{\\AE}Æ","\\text{\\AE}"  },
  {"\\ae","æ\\text{\\ae}æ","\\text{\\ae}"  },
  {"\\alef","ℵ\\alefℵ",""  },
  {"\\alefsym","ℵ\\alefsymℵ",""  },
  {"\\aleph","ℵ\\alephℵ",""  },
  {"{align}","a=b+cd+e=f\\begin{align}a&=b+c\\\\d+e&=f\\end{align}ad+e​=b+c=f​​","\\begin{align}\n   a&=b+c \\\\\n   d+e&=f\n\\end{align}"  },
  {"{align*}","a=b+cd+e=f\\begin{align*}a&=b+c\\\\d+e&=f\\end{align*}ad+e​=b+c=f​","\\begin{align*}\n   a&=b+c \\\\\n   d+e&=f\n\\end{align*}"  },
  {"{aligned}","a=b+cd+e=f\\begin{aligned}a&=b+c\\\\d+e&=f\\end{aligned}ad+e​=b+c=f​","\\begin{aligned}\n   a&=b+c \\\\\n   d+e&=f\n\\end{aligned}"  },
  {"{alignat}","10x+3y=23x+13y=4\\begin{alignat}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignat}103​x+x+​313​y=2y=4​​","\\begin{alignat}{2}\n   10&x+ &3&y = 2 \\\\\n   3&x+&13&y = 4\n\\end{alignat}"  },
  {"{alignat*}","10x+3y=23x+13y=4\\begin{alignat*}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignat*}103​x+x+​313​y=2y=4​","\\begin{alignat*}{2}\n   10&x+ &3&y = 2 \\\\\n   3&x+&13&y = 4\n\\end{alignat*}"  },
  {"{alignedat}","10x+3y=23x+13y=4\\begin{alignedat}{2}10&x+&3&y=2\\\\3&x+&13&y=4\\end{alignedat}103​x+x+​313​y=2y=4​","\\begin{alignedat}{2}\n   10&x+ &3&y = 2 \\\\\n   3&x+&13&y = 4\n\\end{alignedat}"  },
  {"\\allowbreak","",""  },
  {"\\Alpha","A\\AlphaA",""  },
  {"\\alpha","α\\alphaα",""  },
  {"\\amalg","⨿\\amalg⨿",""  },
  {"\\And","&\\And&",""  },
  {"\\and","Not supported","Deprecated"  },
  {"\\ang","Not supported","Deprecated"  },
  {"\\angl","ana_{\\angl n}an​​",""  },
  {"\\angln","ana_\\anglnan​​",""  },
  {"\\angle","∠\\angle∠",""  },
  {"\\approx","≈\\approx≈",""  },
  {"\\approxeq","≊\\approxeq≊",""  },
  {"\\approxcolon","≈:\\approxcolon≈:",""  },
  {"\\approxcoloncolon","≈∷\\approxcoloncolon≈::",""  },
  {"\\arccos","arccos⁡\\arccosarccos",""  },
  {"\\arcctg","arcctg⁡\\arcctgarcctg",""  },
  {"\\arcsin","arcsin⁡\\arcsinarcsin",""  },
  {"\\arctan","arctan⁡\\arctanarctan",""  },
  {"\\arctg","arctg⁡\\arctgarctg",""  },
  {"\\arg","arg⁡\\argarg",""  },
  {"\\argmax","arg max⁡\\argmaxargmax",""  },
  {"\\argmin","arg min⁡\\argminargmin",""  },
  {"{array}","abcd\\begin{array}{cc}a&b\\\\c&d\\end{array}ac​bd​","\\begin{array}{cc}\n   a & b \\\\\n   c & d\n\\end{array}"  },
  {"\\array","Not supported","see {array}"  },
  {"\\arraystretch","abcd\\def\\arraystretch{1.5}\\begin{array}{cc}a&b\\\\c&d\\end{array}ac​bd​","\\def\\arraystretch{1.5}\n\\begin{array}{cc}\n   a & b \\\\\n   c & d\n\\end{array}"  },
  {"\\Arrowvert","Not supported","see \\Vert"  },
  {"\\arrowvert","Not supported","see \\vert"  },
  {"\\ast","∗\\ast∗",""  },
  {"\\asymp","≍\\asymp≍",""  },
  {"\\atop","ab{a \\atop b}ba​","{a \\atop b}"  },
  {"\\atopwithdelims","Not supported",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\backepsilon","∍\\backepsilon∍",""  },
  {"\\backprime","‵\\backprime‵",""  },
  {"\\backsim","∽\\backsim∽",""  },
  {"\\backsimeq","⋍\\backsimeq⋍",""  },
  {"\\backslash","\\\\backslash\\",""  },
  {"\\bar","yˉ\\bar{y}yˉ​","\\bar{y}"  },
  {"\\barwedge","⊼\\barwedge⊼",""  },
  {"\\Bbb","ABC\\Bbb{ABC}ABC","\\Bbb{ABC}\nKaTeX supports A-Z & k"  },
  {"\\Bbbk","k\\Bbbkk",""  },
  {"\\bbox","Not supported",""  },
  {"\\bcancel","5\\bcancel{5}5​","\\bcancel{5}"  },
  {"\\because","∵\\because∵",""  },
  {"\\begin","abcd\\begin{matrix} a & b\\\\ c & d\\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\\\\n   c & d\n\\end{matrix}"  },
  {"\\begingroup","$\\begingroup a}$","\\begingroup a}"  },
  {"\\Beta","B\\BetaB",""  },
  {"\\beta","β\\betaβ",""  },
  {"\\beth","ℶ\\bethℶ",""  },
  {"\\between","≬\\between≬",""  },
  {"\\bf","AaBb12\\bf AaBb12AaBb12","\\bf AaBb12"  },
  {"\\bfseries","Not supported",""  },
  {"\\big","()\\big(\\big)()","\\big(\\big)"  },
  {"\\Big","()\\Big(\\Big)()","\\Big(\\Big)"  },
  {"\\bigcap","⋂\\bigcap⋂",""  },
  {"\\bigcirc","◯\\bigcirc◯",""  },
  {"\\bigcup","⋃\\bigcup⋃",""  },
  {"\\bigg","()\\bigg(\\bigg)()","\\bigg(\\bigg)"  },
  {"\\Bigg","()\\Bigg(\\Bigg)()","\\Bigg(\\Bigg)"  },
  {"\\biggl","(\\biggl((","\\biggl("  },
  {"\\Biggl","(\\Biggl((","\\Biggl("  },
  {"\\biggm","∣\\biggm\\vert​","\\biggm\\vert"  },
  {"\\Biggm","∣\\Biggm\\vert​","\\Biggm\\vert"  },
  {"\\biggr",")\\biggr))","\\biggr)"  },
  {"\\Biggr",")\\Biggr))","\\Biggr)"  },
  {"\\bigl","(\\bigl((","\\bigl("  },
  {"\\Bigl","(\\Bigl((","\\Bigl("  },
  {"\\bigm","∣\\bigm\\vert​","\\bigm\\vert"  },
  {"\\Bigm","∣\\Bigm\\vert​","\\Bigm\\vert"  },
  {"\\bigodot","⨀\\bigodot⨀",""  },
  {"\\bigominus","Not supported","Issue #1222"  },
  {"\\bigoplus","⨁\\bigoplus⨁",""  },
  {"\\bigoslash","Not supported","Issue #1222"  },
  {"\\bigotimes","⨂\\bigotimes⨂",""  },
  {"\\bigr",")\\bigr))","\\bigr)"  },
  {"\\Bigr",")\\Bigr))","\\Bigr)"  },
  {"\\bigsqcap","Not supported","Issue #1222"  },
  {"\\bigsqcup","⨆\\bigsqcup⨆",""  },
  {"\\bigstar","? \\bigstar?",""  },
  {"\\bigtriangledown","▽\\bigtriangledown▽",""  },
  {"\\bigtriangleup","△\\bigtriangleup△",""  },
  {"\\biguplus","⨄\\biguplus⨄",""  },
  {"\\bigvee","⋁\\bigvee⋁",""  },
  {"\\bigwedge","⋀\\bigwedge⋀",""  },
  {"\\binom","(nk)\\binom n k(kn​)","\\binom n k"  },
  {"\\blacklozenge","⧫\\blacklozenge⧫",""  },
  {"\\blacksquare","■\\blacksquare■",""  },
  {"\\blacktriangle","▲\\blacktriangle▲",""  },
  {"\\blacktriangledown","▼\\blacktriangledown▼",""  },
  {"\\blacktriangleleft","◀\\blacktriangleleft◀",""  },
  {"\\blacktriangleright","▶\\blacktriangleright▶",""  },
  {"\\bm","AaBb\\bm{AaBb}AaBb","\\bm{AaBb}"  },
  {"{Bmatrix}","{abcd}\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}{ac​bd​}","\\begin{Bmatrix}\n   a & b \\\\\n   c & d\n\\end{Bmatrix}"  },
  {"{Bmatrix*}","{0−1−10}\\begin{Bmatrix*}{r}0&-1\\\\-1&0\\end{Bmatrix*}{0−1​−10​}","\\begin{Bmatrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{Bmatrix*}"  },
  {"{bmatrix}","{abcd}\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}{ac​bd​}","\\begin{bmatrix}\n   a & b \\\\\n   c & d\n\\end{bmatrix}"  },
  {"{bmatrix*}","{0−1−10}\\begin{bmatrix*}{r}0&-1\\\\-1&0\\end{bmatrix*}{0−1​−10​}","\\begin{bmatrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{bmatrix*}"  },
  {"\\bmod","a mod ba \\bmod bamodb","a \\bmod b"  },
  {"\\bold","AaBb123\\bold{AaBb123}AaBb123","\\bold{AaBb123}"  },
  {"\\boldsymbol","AaBb\\boldsymbol{AaBb}AaBb","\\boldsymbol{AaBb}"  },
  {"\\bot","⊥\\bot⊥",""  },
  {"\\bowtie","⋈\\bowtie⋈",""  },
  {"\\Box","□\\Box□",""  },
  {"\\boxdot","⊡\\boxdot⊡",""  },
  {"\\boxed","ab\\boxed{ab}ab​","\\boxed{ab}"  },
  {"\\boxminus","⊟\\boxminus⊟",""  },
  {"\\boxplus","⊞\\boxplus⊞",""  },
  {"\\boxtimes","⊠\\boxtimes⊠",""  },
  {"\\Bra","⟨ψ∣\\Bra{\\psi}⟨ψ∣","\\Bra{\\psi}"  },
  {"\\bra","⟨ψ∣\\bra{\\psi}⟨ψ∣","\\bra{\\psi}"  },
  {"\\braket","⟨ϕ∣ψ⟩\\braket{\\phi\\VERT\\psi}⟨ϕ∣ψ⟩","\\braket{\\phi|\\psi}"  },
  {"\\Braket","⟨ϕ | ∂2∂t2 | ψ⟩\\Braket{ ϕ \\VERT \\frac{∂^2}{∂ t^2} \\VERT ψ }⟨ϕ​∂t2∂2​​ψ⟩","\\Braket{ ϕ | \\frac{∂^2}{∂ t^2} | ψ }"  },
  {"\\brace","{nk}{n\\brace k}{kn​}","{n\\brace k}"  },
  {"\\bracevert","Not supported",""  },
  {"\\brack","{nk}{n\\brack k}{kn​}","{n\\brack k}"  },
  {"\\breve","eu˘\\breve{eu}eu˘","\\breve{eu}"  },
  {"\\buildrel","Not supported",""  },
  {"\\bull","∙\\bull∙",""  },
  {"\\bullet","∙\\bullet∙",""  },
  {"\\Bumpeq","≎\\Bumpeq≎",""  },
  {"\\bumpeq","≏\\bumpeq≏",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\C","Not supported","Deprecated"  },
  {"\\cal","AaBb123\\cal AaBb123AaBb123","\\cal AaBb123"  },
  {"\\cancel","5\\cancel{5}5​","\\cancel{5}"  },
  {"\\cancelto","Not supported",""  },
  {"\\Cap","⋒\\Cap⋒",""  },
  {"\\cap","∩\\cap∩",""  },
  {"{cases}","{aif bcif d\\begin{cases}a&\\text{if }b\\\\c&\\text{if }d\\end{cases}{ac​if bif d​","\\begin{cases}\n   a &\\text{if } b \\\\\n   c &\\text{if } d\n\\end{cases}"  },
  {"\\cases","Not supported","see {cases}"  },
  {"{CD}","A→aBb↓↑cC=D\\begin{CD}A @>a>> B \\\\@VbVV @AAcA\\\\C @= D\\end{CD}Ab↓⏐​C​a​​B⏐↑​cD​","\\begin{CD}\n   A @>a>> B \\\\\n@VbVV @AAcA \\\\\n   C @= D\n\\end{CD}"  },
  {"\\cdot","? \\cdot?",""  },
  {"\\cdotp","? \\cdotp?",""  },
  {"\\cdots","⋯\\cdots⋯",""  },
  {"\\ce","CX6HX5−CHO{\\mathrm{C}{\\vphantom{X}}_{\\smash{t}{6}}\\mathrm{H}{\\vphantom{X}}_{\\smash{t}{5}}{-}\\mathrm{CHO}}CX6​HX5​−CHO","\\ce{C6H5-CHO} Requires an extension"  },
  {"\\cee","Not supported","Deprecated by mhchem"  },
  {"\\centerdot","a? ba\\centerdot ba? b","a\\centerdot b"  },
  {"\\cf","Not supported","Deprecated by mhchem;"  },
  {"use \\ce instead","",""  },
  {"\\cfrac","21+21+21\\cfrac{2}{1+\\cfrac{2}{1+\\cfrac{2}{1}}}1+1+12​2​2​","\\cfrac{2}{1+\\cfrac{2}{1+\\cfrac{2}{1}}}"  },
  {"\\char","☺\\char\"263a☺","\\char\"263a"  },
  {"\\check","oeˇ\\check{oe}oeˇ","\\check{oe}"  },
  {"\\ch","ch⁡\\chch",""  },
  {"\\checkmark","✓\\checkmark✓",""  },
  {"\\Chi","X\\ChiX",""  },
  {"\\chi","χ\\chiχ",""  },
  {"\\choose","(n+1k+2){n+1 \\choose k+2}(k+2n+1​)","{n+1 \\choose k+2}"  },
  {"\\circ","∘\\circ∘",""  },
  {"\\circeq","≗\\circeq≗",""  },
  {"\\circlearrowleft","↺\\circlearrowleft↺",""  },
  {"\\circlearrowright","↻\\circlearrowright↻",""  },
  {"\\circledast","⊛\\circledast⊛",""  },
  {"\\circledcirc","⊚\\circledcirc⊚",""  },
  {"\\circleddash","⊝\\circleddash⊝",""  },
  {"\\circledR","®\\circledR®",""  },
  {"\\circledS","Ⓢ\\circledSⓈ",""  },
  {"\\class","Not supported","A PR is pending."  },
  {"\\cline","Not supported","Issue #269"  },
  {"\\clubs","♣\\clubs♣",""  },
  {"\\clubsuit","♣\\clubsuit♣",""  },
  {"\\cnums","C\\cnumsC",""  },
  {"\\colon","⁣:\\colon:",""  },
  {"\\Colonapprox","∷≈\\Colonapprox::≈",""  },
  {"\\colonapprox",":≈\\colonapprox:≈",""  },
  {"\\coloncolon","∷\\coloncolon::",""  },
  {"\\coloncolonapprox","∷≈\\coloncolonapprox::≈",""  },
  {"\\coloncolonequals","∷=\\coloncolonequals::=",""  },
  {"\\coloncolonminus","∷−\\coloncolonminus::−",""  },
  {"\\coloncolonsim","∷∼\\coloncolonsim::∼",""  },
  {"\\Coloneq","∷−\\Coloneq::−",""  },
  {"\\coloneq",":−\\coloneq:−",""  },
  {"\\colonequals","≔\\colonequals:=",""  },
  {"\\Coloneqq","∷=\\Coloneqq::=",""  },
  {"\\coloneqq","≔\\coloneqq:=",""  },
  {"\\colonminus",":−\\colonminus:−",""  },
  {"\\Colonsim","∷∼\\Colonsim::∼",""  },
  {"\\colonsim",":∼\\colonsim:∼",""  },
  {"\\color","AaBb123\\color{#0000FF} AaBb123AaBb123","\\color{#0000FF} AaBb123"  },
  {"\\colorbox","Black on red\\colorbox{red}{Black on red}Black on red​","\\colorbox{red}{Black on red}"  },
  {"\\complement","∁\\complement∁",""  },
  {"\\Complex","C\\ComplexC",""  },
  {"\\cong","? \\cong?",""  },
  {"\\Coppa","Not supported",""  },
  {"\\coppa","Not supported",""  },
  {"\\coprod","∐\\coprod∐",""  },
  {"\\copyright","©\\copyrightc◯",""  },
  {"\\cos","cos⁡\\coscos",""  },
  {"\\cosec","cosec⁡\\coseccosec",""  },
  {"\\cosh","cosh⁡\\coshcosh",""  },
  {"\\cot","cot⁡\\cotcot",""  },
  {"\\cotg","cotg⁡\\cotgcotg",""  },
  {"\\coth","coth⁡\\cothcoth",""  },
  {"\\cr","abcd\\begin{matrix} a & b\\cr c & d \\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\cr\n   c & d\n\\end{matrix}"  },
  {"\\csc","csc⁡\\csccsc",""  },
  {"\\cssId","Not supported","A PR is pending."  },
  {"\\ctg","ctg⁡\\ctgctg",""  },
  {"\\cth","cth⁡\\cthcth",""  },
  {"\\Cup","⋓\\Cup⋓",""  },
  {"\\cup","∪\\cup∪",""  },
  {"\\curlyeqprec","⋞\\curlyeqprec⋞",""  },
  {"\\curlyeqsucc","⋟\\curlyeqsucc⋟",""  },
  {"\\curlyvee","⋎\\curlyvee⋎",""  },
  {"\\curlywedge","⋏\\curlywedge⋏",""  },
  {"\\curvearrowleft","↶\\curvearrowleft↶",""  },
  {"\\curvearrowright","↷\\curvearrowright↷",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\dag","†\\dag†",""  },
  {"\\Dagger","‡\\Dagger‡",""  },
  {"\\dagger","†\\dagger†",""  },
  {"\\daleth","ℸ\\dalethℸ",""  },
  {"\\Darr","⇓\\Darr⇓",""  },
  {"\\dArr","⇓\\dArr⇓",""  },
  {"\\darr","↓\\darr↓",""  },
  {"{darray}","abcd\\begin{darray}{cc}a&b\\\\c&d\\end{darray}ac​bd​","\\begin{darray}{cc}\n   a & b \\\\\n   c & d\n\\end{darray}"  },
  {"\\dashleftarrow","⇠\\dashleftarrow⇠",""  },
  {"\\dashrightarrow","⇢\\dashrightarrow⇢",""  },
  {"\\dashv","⊣\\dashv⊣",""  },
  {"\\dbinom","(nk)\\dbinom n k(kn​)","\\dbinom n k"  },
  {"\\dblcolon","∷\\dblcolon::",""  },
  {"{dcases}","{aif bcif d\\begin{dcases}a&\\text{if }b\\\\c&\\text{if }d\\end{dcases}{ac​if bif d​","\\begin{dcases}\n   a &\\text{if } b \\\\\n   c &\\text{if } d\n\\end{dcases}"  },
  {"\\ddag","‡\\ddag‡",""  },
  {"\\ddagger","‡\\ddagger‡",""  },
  {"\\ddddot","Not supported",""  },
  {"\\dddot","Not supported",""  },
  {"\\ddot","x¨\\ddot xx¨","\\ddot x"  },
  {"\\ddots","⋱\\ddots⋱",""  },
  {"\\DeclareMathOperator","Not supported",""  },
  {"\\def","x2+x2\\def\\foo{x^2} \\foo + \\foox2+x2","\\def\\foo{x^2} \\foo + \\foo"  },
  {"\\definecolor","Not supported","Issue #750"  },
  {"\\deg","deg⁡\\degdeg",""  },
  {"\\degree","°\\degree°",""  },
  {"\\delta","δ\\deltaδ",""  },
  {"\\Delta","Δ\\DeltaΔ",""  },
  {"\\det","det⁡\\detdet",""  },
  {"\\Digamma","Not supported",""  },
  {"\\digamma","ϝ\\digammaϝ",""  },
  {"\\dfrac","a−1b−1\\dfrac{a-1}{b-1}b−1a−1​","\\dfrac{a-1}{b-1}"  },
  {"\\diagdown","╲\\diagdown╲",""  },
  {"\\diagup","╱\\diagup╱",""  },
  {"\\Diamond","◊\\Diamond◊",""  },
  {"\\diamond","⋄\\diamond⋄",""  },
  {"\\diamonds","♢\\diamonds♢",""  },
  {"\\diamondsuit","♢\\diamondsuit♢",""  },
  {"\\dim","dim⁡\\dimdim",""  },
  {"\\displaylines","Not supported",""  },
  {"\\displaystyle","∑0n\\displaystyle\\sum_0^n0∑n​","\\displaystyle\\sum_0^n"  },
  {"\\div","÷\\div÷",""  },
  {"\\divideontimes","⋇\\divideontimes⋇",""  },
  {"\\dot","x˙\\dot xx˙","\\dot x"  },
  {"\\Doteq","≑\\Doteq≑",""  },
  {"\\doteq","≐\\doteq≐",""  },
  {"\\doteqdot","≑\\doteqdot≑",""  },
  {"\\dotplus","∔\\dotplus∔",""  },
  {"\\dots","x1+⋯+xnx_1 + \\dots + x_nx1​+⋯+xn​","x_1 + \\dots + x_n"  },
  {"\\dotsb","x1+⋯+xnx_1 +\\dotsb + x_nx1​+⋯+xn​","x_1 +\\dotsb + x_n"  },
  {"\\dotsc","x,…,yx,\\dotsc,yx,…,y","x,\\dotsc,y"  },
  {"\\dotsi","∫A1∫A2 ⁣⋯\\int_{A_1}\\int_{A_2}\\dotsi∫A1​​∫A2​​⋯","\\int_{A_1}\\int_{A_2}\\dotsi"  },
  {"\\dotsm","x1x2⋯xnx_1 x_2 \\dotsm x_nx1​x2​⋯xn​","$x_1 x_2 \\dotsm x_n"  },
  {"\\dotso","…\\dotso…",""  },
  {"\\doublebarwedge","⩞\\doublebarwedge⩞",""  },
  {"\\doublecap","⋒\\doublecap⋒",""  },
  {"\\doublecup","⋓\\doublecup⋓",""  },
  {"\\Downarrow","⇓\\Downarrow⇓",""  },
  {"\\downarrow","↓\\downarrow↓",""  },
  {"\\downdownarrows","⇊\\downdownarrows⇊",""  },
  {"\\downharpoonleft","⇃\\downharpoonleft⇃",""  },
  {"\\downharpoonright","⇂\\downharpoonright⇂",""  },
  {"{drcases}","aif bcif d}\\begin{drcases}a&\\text{if }b\\\\c&\\text{if }d\\end{drcases}ac​if bif d​}","\\begin{drcases}\n   a &\\text{if } b \\\\\n   c &\\text{if } d\n\\end{drcases}"  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\edef","a\\def\\foo{a}\\edef\\fcopy{\\foo}\\def\\foo{}\\fcopya","\\def\\foo{a}\\edef\\fcopy{\\foo}\\def\\foo{}\\fcopy"  },
  {"\\ell","ℓ\\ellℓ",""  },
  {"\\else","Not supported","Issue #1003"  },
  {"\\em","Not supported",""  },
  {"\\emph","Not supported",""  },
  {"\\empty","? \\empty?",""  },
  {"\\emptyset","? \\emptyset?",""  },
  {"\\enclose","Not supported","Non standard"  },
  {"\\end","abcd\\begin{matrix} a & b\\\\ c & d\\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\\\\n   c & d\n\\end{matrix}"  },
  {"\\endgroup","${a\\endgroup$","{a\\endgroup"  },
  {"\\enspace","aba\\enspace bab","a\\enspace b"  },
  {"\\Epsilon","E\\EpsilonE",""  },
  {"\\epsilon","ϵ\\epsilonϵ",""  },
  {"\\eqalign","Not supported",""  },
  {"\\eqalignno","Not supported",""  },
  {"\\eqcirc","≖\\eqcirc≖",""  },
  {"\\Eqcolon","−∷\\Eqcolon−::",""  },
  {"\\eqcolon","∹\\eqcolon−:",""  },
  {"{equation}","a=b+c\\begin{equation}a = b + c\\end{equation}a=b+c​​","\\begin{equation}\n   a = b + c\n\\end{equation}"  },
  {"{equation*}","a=b+c\\begin{equation*}a = b + c\\end{equation*}a=b+c​","\\begin{equation*}\n   a = b + c\n\\end{equation*}"  },
  {"{eqnarray}","Not supported",""  },
  {"\\Eqqcolon","=∷\\Eqqcolon=::",""  },
  {"\\eqqcolon","≕\\eqqcolon=:",""  },
  {"\\eqref","Not supported","Issue #350"  },
  {"\\eqsim","≂\\eqsim≂",""  },
  {"\\eqslantgtr","⪖\\eqslantgtr⪖",""  },
  {"\\eqslantless","⪕\\eqslantless⪕",""  },
  {"\\equalscolon","≕\\equalscolon=:",""  },
  {"\\equalscoloncolon","=∷\\equalscoloncolon=::",""  },
  {"\\equiv","≡\\equiv≡",""  },
  {"\\Eta","H\\EtaH",""  },
  {"\\eta","η\\etaη",""  },
  {"\\eth","ð\\ethð",""  },
  {"\\euro","Not supported",""  },
  {"\\exist","∃\\exist∃",""  },
  {"\\exists","∃\\exists∃",""  },
  {"\\exp","exp⁡\\expexp",""  },
  {"\\expandafter","",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\fallingdotseq","≒\\fallingdotseq≒",""  },
  {"\\fbox","Hi there!\\fbox{Hi there!}Hi there!​","\\fbox{Hi there!}"  },
  {"\\fcolorbox","A\\fcolorbox{red}{aqua}{A}A​","\\fcolorbox{red}{aqua}{A}"  },
  {"\\fi","Not supported","Issue #1003"  },
  {"\\Finv","Ⅎ\\FinvℲ",""  },
  {"\\flat","♭\\flat♭",""  },
  {"\\footnotesize","footnotesize\\footnotesize footnotesizefootnotesize","\\footnotesize footnotesize"  },
  {"\\forall","∀\\forall∀",""  },
  {"\\frac","ab\\frac a bba​","\\frac a b"  },
  {"\\frak","AaBb\\frak{AaBb}AaBb","\\frak{AaBb}"  },
  {"\\frown","⌢\\frown⌢",""  },
  {"\\futurelet","",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\Game","? ?\\Game? ?",""  },
  {"\\Gamma","Γ\\GammaΓ",""  },
  {"\\gamma","γ\\gammaγ",""  },
  {"{gather}","a=be=b+c\\begin{gather}a=b\\\\e=b+c\\end{gather}a=be=b+c​​","\\begin{gather}\n   a=b \\\\\n   e=b+c\n\\end{gather}"  },
  {"{gathered}","a=be=b+c\\begin{gathered}a=b\\\\e=b+c\\end{gathered}a=be=b+c​","\\begin{gathered}\n   a=b \\\\\n   e=b+c\n\\end{gathered}"  },
  {"\\gcd","gcd⁡\\gcdgcd",""  },
  {"\\gdef","y2+y2\\gdef\\sqr#1{#1^2} \\sqr{y} + \\sqr{y}y2+y2","\\gdef\\sqr#1{#1^2} \\sqr{y} + \\sqr{y}"  },
  {"\\ge","≥\\ge≥",""  },
  {"\\geneuro","Not supported",""  },
  {"\\geneuronarrow","Not supported",""  },
  {"\\geneurowide","Not supported",""  },
  {"\\genfrac","(aa+1}\\genfrac ( } {2pt}{0}a{a+1}(a+1a​}","\\genfrac ( } {2pt}{0}a{a+1}"  },
  {"\\geq","≥\\geq≥",""  },
  {"\\geqq","≧\\geqq≧",""  },
  {"\\geqslant","⩾\\geqslant⩾",""  },
  {"\\gets","←\\gets←",""  },
  {"\\gg","≫\\gg≫",""  },
  {"\\ggg","⋙\\ggg⋙",""  },
  {"\\gggtr","⋙\\gggtr⋙",""  },
  {"\\gimel","ℷ\\gimelℷ",""  },
  {"\\global","2+3\\global\\def\\add#1#2{#1+#2} \\add 2 32+3","\\global\\def\\add#1#2{#1+#2} \\add 2 3"  },
  {"\\gnapprox","⪊\\gnapprox⪊",""  },
  {"\\gneq","⪈\\gneq⪈",""  },
  {"\\gneqq","≩\\gneqq≩",""  },
  {"\\gnsim","⋧\\gnsim⋧",""  },
  {"\\grave","euˋ\\grave{eu}euˋ","\\grave{eu}"  },
  {"\\gt","a>ba \\gt ba>b","a \\gt b"  },
  {"\\gtrdot","⋗\\gtrdot⋗",""  },
  {"\\gtrapprox","⪆\\gtrapprox⪆",""  },
  {"\\gtreqless","⋛\\gtreqless⋛",""  },
  {"\\gtreqqless","⪌\\gtreqqless⪌",""  },
  {"\\gtrless","≷\\gtrless≷",""  },
  {"\\gtrsim","≳\\gtrsim≳",""  },
  {"\\gvertneqq","≩\\gvertneqq",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\H","a˝\\text{\\H{a}}a˝","\\text{\\H{a}}"  },
  {"\\Harr","⇔\\Harr⇔",""  },
  {"\\hArr","⇔\\hArr⇔",""  },
  {"\\harr","↔\\harr↔",""  },
  {"\\hat","θ^\\hat{\\theta}θ^","\\hat{\\theta}"  },
  {"\\hbar","ℏ\\hbarℏ",""  },
  {"\\hbox","x2\\hbox{$x^2$}x2","\\hbox{$x^2$}"  },
  {"\\hbox to","Not supported",""  },
  {"\\hdashline","abcd\\begin{matrix}a&b\\\\ \\hdashline c &d\\end{matrix}ac​bd​​","\\begin{matrix}\n   a & b \\\\\n   \\hdashline\n   c & d\n\\end{matrix}"  },
  {"\\hearts","♡\\hearts♡",""  },
  {"\\heartsuit","♡\\heartsuit♡",""  },
  {"\\hfil","Not supported",""  },
  {"\\hfill","Not supported","Issues #164 & #269"  },
  {"\\hline","abcd\\begin{matrix}a&b\\\\ \\hline c &d\\end{matrix}ac​bd​​","\\begin{matrix}\n   a & b \\\\ \\hline\n   c & d\n\\end{matrix}"  },
  {"\\hom","hom⁡\\homhom",""  },
  {"\\hookleftarrow","↩\\hookleftarrow↩",""  },
  {"\\hookrightarrow","↪\\hookrightarrow↪",""  },
  {"\\hphantom","abcda\\hphantom{bc}dabcd","a\\hphantom{bc}d"  },
  {"\\href","KaTeX\\href{https://katex.org/}{\\KaTeX}KATE​X","\\href{https://katex.org/}{\\KaTeX} Requires trust option"  },
  {"\\hskip","widw\\hskip1em i\\hskip2em dwid","w\\hskip1em i\\hskip2em d"  },
  {"\\hslash","ℏ\\hslashℏ",""  },
  {"\\hspace","s\\hspace7ex k","s\\hspace7ex k"  },
  {"\\htmlClass","x\\htmlClass{foo}{x}x","\\htmlClass{foo}{x} Must enable trust and disable strict option"  },
  {"\\htmlData","x\\htmlData{foo=a, bar=b}{x}x","\\htmlData{foo=a, bar=b}{x} Must enable trust and disable strict option"  },
  {"\\htmlId","x\\htmlId{bar}{x}x","\\htmlId{bar}{x} Must enable trust and disable strict option"  },
  {"\\htmlStyle","x\\htmlStyle{color: red;}{x}x","\\htmlStyle{color: red;}{x} Must enable trust and disable strict option"  },
  {"\\huge","huge\\huge hugehuge","\\huge huge"  },
  {"\\Huge","Huge\\Huge HugeHuge","\\Huge Huge"  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\i","ı\\text{\\i}ı","\\text{\\i}"  },
  {"\\idotsint","Not supported",""  },
  {"\\iddots","Not supported","Issue #1223"  },
  {"\\if","Not supported","Issue #1003"  },
  {"\\iff","A?  ⟺?  BA\\iff BA⟺B","A\\iff B"  },
  {"\\ifmode","Not supported","Issue #1003"  },
  {"\\ifx","Not supported","Issue #1003"  },
  {"\\iiiint","Not supported",""  },
  {"\\iiint","∭\\iiint∭",""  },
  {"\\iint","∬\\iint∬",""  },
  {"\\Im","ℑ\\Imℑ",""  },
  {"\\image","ℑ\\imageℑ",""  },
  {"\\imageof","⊷\\imageof⊷",""  },
  {"\\imath","ı\\imath",""  },
  {"\\impliedby","P?  ⟸?  QP\\impliedby QP⟸Q","P\\impliedby Q"  },
  {"\\implies","P?  ⟹?  QP\\implies QP⟹Q","P\\implies Q"  },
  {"\\in","∈\\in∈",""  },
  {"\\includegraphics","\\includegraphics{height=0.8em, totalheight=0.9em, width=0.9em, alt=KA logo}{https://cdn.kastatic.org/images/apple-touch-icon-57x57-precomposed.new.png}","\\includegraphics{height=0.8em, totalheight=0.9em, width=0.9em, alt=KA logo}{https://cdn.kastatic.org/images/apple-touch-icon-57x57-precomposed.new.png} Requires trust option"  },
  {"\\inf","inf⁡\\infinf",""  },
  {"\\infin","∞\\infin∞",""  },
  {"\\infty","∞\\infty∞",""  },
  {"\\injlim","inj lim⁡\\injliminjlim","\\injlim"  },
  {"\\int","∫\\int∫",""  },
  {"\\intercal","⊺\\intercal⊺",""  },
  {"\\intop","∫\\intop∫",""  },
  {"\\Iota","I\\IotaI",""  },
  {"\\iota","ι\\iotaι",""  },
  {"\\isin","∈\\isin∈",""  },
  {"\\it","AaBb{\\it AaBb}AaBb","{\\it AaBb}"  },
  {"\\itshape","Not supported",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\j","ȷ\\text{\\j}ȷ","\\text{\\j}"  },
  {"\\jmath","ȷ\\jmath",""  },
  {"\\Join","⋈\\Join⋈",""  },
  {"\\Kappa","K\\KappaK",""  },
  {"\\kappa","κ\\kappaκ",""  },
  {"\\KaTeX","KaTeX\\KaTeXKATE​X",""  },
  {"\\ker","ker⁡\\kerker",""  },
  {"\\kern","IRI\\kern-2.5pt RIR","I\\kern-2.5pt R"  },
  {"\\Ket","∣ψ⟩\\Ket{\\psi}∣ψ⟩","\\Ket{\\psi}"  },
  {"\\ket","∣ψ⟩\\ket{\\psi}∣ψ⟩","\\ket{\\psi}"  },
  {"\\Koppa","Not supported",""  },
  {"\\koppa","Not supported",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\L","Not supported",""  },
  {"\\l","Not supported",""  },
  {"\\Lambda","Λ\\LambdaΛ",""  },
  {"\\lambda","λ\\lambdaλ",""  },
  {"\\label","Not supported",""  },
  {"\\land","∧\\land∧",""  },
  {"\\lang","⟨A⟩\\lang A\\rangle⟨A⟩","\\lang A\\rangle"  },
  {"\\langle","⟨A⟩\\langle A\\rangle⟨A⟩","\\langle A\\rangle"  },
  {"\\Larr","⇐\\Larr⇐",""  },
  {"\\lArr","⇐\\lArr⇐",""  },
  {"\\larr","←\\larr←",""  },
  {"\\large","large\\large largelarge","\\large large"  },
  {"\\Large","Large\\Large LargeLarge","\\Large Large"  },
  {"\\LARGE","LARGE\\LARGE LARGELARGE","\\LARGE LARGE"  },
  {"\\LaTeX","LaTeX\\LaTeXLATE​X",""  },
  {"\\lBrace","⦃\\lBrace{{",""  },
  {"\\lbrace","{\\lbrace{",""  },
  {"\\lbrack","{\\lbrack{",""  },
  {"\\lceil","⌈\\lceil⌈",""  },
  {"\\ldotp",".\\ldotp.",""  },
  {"\\ldots","…\\ldots…",""  },
  {"\\le","≤\\le≤",""  },
  {"\\leadsto","⇝\\leadsto⇝",""  },
  {"\\left","{ab\\left\\lbrace \\dfrac ab \\right.{ba​","\\left\\lbrace \\dfrac ab \\right."  },
  {"\\leftarrow","←\\leftarrow←",""  },
  {"\\Leftarrow","⇐\\Leftarrow⇐",""  },
  {"\\LeftArrow","Not supported","Non standard"  },
  {"\\leftarrowtail","↢\\leftarrowtail↢",""  },
  {"\\leftharpoondown","↽\\leftharpoondown↽",""  },
  {"\\leftharpoonup","↼\\leftharpoonup↼",""  },
  {"\\leftleftarrows","⇇\\leftleftarrows⇇",""  },
  {"\\Leftrightarrow","⇔\\Leftrightarrow⇔",""  },
  {"\\leftrightarrow","↔\\leftrightarrow↔",""  },
  {"\\leftrightarrows","⇆\\leftrightarrows⇆",""  },
  {"\\leftrightharpoons","⇋\\leftrightharpoons⇋",""  },
  {"\\leftrightsquigarrow","↭\\leftrightsquigarrow↭",""  },
  {"\\leftroot","Not supported",""  },
  {"\\leftthreetimes","⋋\\leftthreetimes⋋",""  },
  {"\\leq","≤\\leq≤",""  },
  {"\\leqalignno","Not supported",""  },
  {"\\leqq","≦\\leqq≦",""  },
  {"\\leqslant","⩽\\leqslant⩽",""  },
  {"\\lessapprox","? \\lessapprox?",""  },
  {"\\lessdot","⋖\\lessdot⋖",""  },
  {"\\lesseqgtr","⋚\\lesseqgtr⋚",""  },
  {"\\lesseqqgtr","⪋\\lesseqqgtr⪋",""  },
  {"\\lessgtr","≶\\lessgtr≶",""  },
  {"\\lesssim","≲\\lesssim≲",""  },
  {"\\let","",""  },
  {"\\lfloor","⌊\\lfloor⌊",""  },
  {"\\lg","lg⁡\\lglg",""  },
  {"\\lgroup","⟮\\lgroup⟮",""  },
  {"\\lhd","⊲\\lhd⊲",""  },
  {"\\lim","lim⁡\\limlim",""  },
  {"\\liminf","lim inf⁡\\liminfliminf",""  },
  {"\\limits","lim⁡x\\lim\\limits_xxlim​","\\lim\\limits_x"  },
  {"\\limsup","lim sup⁡\\limsuplimsup",""  },
  {"\\ll","≪\\ll≪",""  },
  {"\\llap","=/ {=}\\llap{/\\,}=/","{=}\\llap{/\\,}"  },
  {"\\llbracket","⟦\\llbracket{{",""  },
  {"\\llcorner","⌞\\llcorner└",""  },
  {"\\Lleftarrow","⇚\\Lleftarrow⇚",""  },
  {"\\lll","⋘\\lll⋘",""  },
  {"\\llless","⋘\\llless⋘",""  },
  {"\\lmoustache","⎰\\lmoustache⎰",""  },
  {"\\ln","ln⁡\\lnln",""  },
  {"\\lnapprox","⪉\\lnapprox⪉",""  },
  {"\\lneq","⪇\\lneq⪇",""  },
  {"\\lneqq","≨\\lneqq≨",""  },
  {"\\lnot","¬\\lnot¬",""  },
  {"\\lnsim","⋦\\lnsim⋦",""  },
  {"\\log","log⁡\\loglog",""  },
  {"\\long","",""  },
  {"\\Longleftarrow","⟸\\Longleftarrow⟸",""  },
  {"\\longleftarrow","⟵\\longleftarrow⟵",""  },
  {"\\Longleftrightarrow","⟺\\Longleftrightarrow⟺",""  },
  {"\\longleftrightarrow","⟷\\longleftrightarrow⟷",""  },
  {"\\longmapsto","⟼\\longmapsto⟼",""  },
  {"\\Longrightarrow","⟹\\Longrightarrow⟹",""  },
  {"\\longrightarrow","⟶\\longrightarrow⟶",""  },
  {"\\looparrowleft","↫\\looparrowleft↫",""  },
  {"\\looparrowright","↬\\looparrowright↬",""  },
  {"\\lor","∨\\lor∨",""  },
  {"\\lower","Not supported",""  },
  {"\\lozenge","◊\\lozenge◊",""  },
  {"\\lparen","(\\lparen(",""  },
  {"\\Lrarr","⇔\\Lrarr⇔",""  },
  {"\\lrArr","⇔\\lrArr⇔",""  },
  {"\\lrarr","↔\\lrarr↔",""  },
  {"\\lrcorner","⌟\\lrcorner┘",""  },
  {"\\lq","‘\\lq‘",""  },
  {"\\Lsh","↰\\Lsh↰",""  },
  {"\\lt","<\\lt<",""  },
  {"\\ltimes","⋉\\ltimes⋉",""  },
  {"\\lVert","∥\\lVert∥",""  },
  {"\\lvert","∣\\lvert∣",""  },
  {"\\lvertneqq","≨\\lvertneqq",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\maltese","✠\\maltese✠",""  },
  {"\\mapsto","↦\\mapsto↦",""  },
  {"\\mathbb","AB\\mathbb{AB}AB","\\mathbb{AB}\nKaTeX supports A-Z k"  },
  {"\\mathbf","AaBb123\\mathbf{AaBb123}AaBb123","\\mathbf{AaBb123}"  },
  {"\\mathbin","a!ba\\mathbin{!}ba!b","a\\mathbin{!}b"  },
  {"\\mathcal","AaBb123\\mathcal{AaBb123}AaBb123","\\mathcal{AaBb123}"  },
  {"\\mathchoice","a  ba\\mathchoice{\\,}{\\,\\,}{\\,\\,\\,}{\\,\\,\\,\\,}bab","a\\mathchoice{\\,}{\\,\\,}{\\,\\,\\,}{\\,\\,\\,\\,}b"  },
  {"\\mathclap","∑1≤i≤nxi\\displaystyle\\sum_{\\mathclap{1\\le i\\le n}} x_{i}1≤i≤n∑​xi​","\\sum_{\\mathclap{1\\le i\\le n}} x_{i}"  },
  {"\\mathclose","a+(b>+ca + (b\\mathclose\\gt + ca+(b>+c","a + (b\\mathclose\\gt + c"  },
  {"\\mathellipsis","…\\mathellipsis…",""  },
  {"\\mathfrak","AaBb\\mathfrak{AaBb}AaBb","\\mathfrak{AaBb}\nKaTeX supports A-Za-z"  },
  {"\\mathinner","abinsidecdab\\mathinner{\\text{inside}}cdabinsidecd","ab\\mathinner{\\text{inside}}cd"  },
  {"\\mathit","AaBb\\mathit{AaBb}AaBb","\\mathit{AaBb}\nKaTeX supports A-Za-z"  },
  {"\\mathllap","=/ {=}\\mathllap{/\\,}=/","{=}\\mathllap{/\\,}"  },
  {"\\mathnormal","AaBb\\mathnormal{AaBb}AaBb","\\mathnormal{AaBb}\nKaTeX supports A-Za-z"  },
  {"\\mathop","⋆ab\\mathop{\\star}_a^b⋆ab​","\\mathop{\\star}_a^b"  },
  {"\\mathopen","a+<b)+ca + \\mathopen\\lt b) + ca+<b)+c","a + \\mathopen\\lt b) + c"  },
  {"\\mathord","1,234,5671\\mathord{,}234{,}5671,234,567","1\\mathord{,}234{,}567"  },
  {"\\mathpunct","A−BA\\mathpunct{-}BA−B","A\\mathpunct{-}B"  },
  {"\\mathrel","a#ba \\mathrel{\\#} ba#b","a \\mathrel{\\#} b"  },
  {"\\mathrlap","/=\\mathrlap{\\,/}{=}/=","\\mathrlap{\\,/}{=}"  },
  {"\\mathring","a˚\\mathring{a}a˚","\\mathring{a}"  },
  {"\\mathrm","AaBb123\\mathrm{AaBb123}AaBb123","\\mathrm{AaBb123}"  },
  {"\\mathscr","AB\\mathscr{AB}AB","\\mathscr{AaBb123}\nKaTeX supports A-Z"  },
  {"\\mathsf","AaBb123\\mathsf{AaBb123}AaBb123","\\mathsf{AaBb123}"  },
  {"\\mathsterling","£\\mathsterling£",""  },
  {"\\mathstrut","(a\\sqrt{\\mathstrut a}(a​","\\sqrt{\\mathstrut a}"  },
  {"\\mathtip","Not supported",""  },
  {"\\mathtt","AaBb123\\mathtt{AaBb123}AaBb123","\\mathtt{AaBb123}"  },
  {"\\matrix","Not supported","See {matrix}"  },
  {"{matrix}","abcd\\begin{matrix}a&b\\\\c&d\\end{matrix}ac​bd​","\\begin{matrix}\n   a & b \\\\\n   c & d\n\\end{matrix}"  },
  {"{matrix*}","0−1−10\\begin{matrix*}{r}0&-1\\\\-1&0\\end{matrix*}0−1​−10​","\\begin{matrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{matrix*}"  },
  {"\\max","max⁡\\maxmax",""  },
  {"\\mbox","Not supported",""  },
  {"\\md","Not supported",""  },
  {"\\mdseries","Not supported",""  },
  {"\\measuredangle","∡\\measuredangle∡",""  },
  {"\\medspace","a? ba\\medspace bab","a\\medspace b"  },
  {"\\mho","℧\\mho℧",""  },
  {"\\mid","{x∈R∣x>0}\\{x∈ℝ\\mid x>0\\}{x∈R∣x>0}","\\{x∈ℝ\\mid x>0\\}"  },
  {"\\middle","P(A|B)P\\left(A\\middle\\vert B\\right)P(A∣B)","P\\left(A\\middle\\vert B\\right)"  },
  {"\\min","min⁡\\minmin",""  },
  {"\\minuscolon","∹\\minuscolon−:",""  },
  {"\\minuscoloncolon","−∷\\minuscoloncolon−::",""  },
  {"\\minuso","⦵\\minuso∘−",""  },
  {"\\mit","Not supported","See \\mathit"  },
  {"\\mkern","aba\\mkern18mu bab","a\\mkern18mu b"  },
  {"\\mmlToken","Not supported",""  },
  {"\\mod","3≡5mod  23\\equiv 5 \\mod 23≡5mod2","3\\equiv 5 \\mod 2"  },
  {"\\models","⊨\\models⊨",""  },
  {"\\moveleft","Not supported",""  },
  {"\\moveright","Not supported",""  },
  {"\\mp","∓\\mp∓",""  },
  {"\\mskip","aba\\mskip{10mu}bab","a\\mskip{10mu}b"  },
  {"\\mspace","Not supported",""  },
  {"\\Mu","M\\MuM",""  },
  {"\\mu","μ\\muμ",""  },
  {"\\multicolumn","Not supported","Issue #269"  },
  {"{multiline}","Not supported",""  },
  {"\\multimap","⊸\\multimap⊸",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"null","N\\NN",""  },
  {"\\nabla","∇\\nabla∇",""  },
  {"\\natnums","N\\natnumsN",""  },
  {"\\natural","♮\\natural♮",""  },
  {"\\negmedspace","a ⁣ba\\negmedspace bab","a\\negmedspace b"  },
  {"\\ncong","≆\\ncong≆",""  },
  {"\\ne","≠\\ne=",""  },
  {"\\nearrow","↗\\nearrow↗",""  },
  {"\\neg","¬\\neg¬",""  },
  {"\\negthickspace","a? ⁣ba\\negthickspace bab","a\\negthickspace b"  },
  {"\\negthinspace","a ⁣ba\\negthinspace bab","a\\negthinspace b"  },
  {"\\neq","≠\\neq=",""  },
  {"\\newcommand","✓\\newcommand\\chk{\\checkmark} \\chk✓","\\newcommand\\chk{\\checkmark} \\chk"  },
  {"\\newenvironment","Not supported","Issue #37"  },
  {"\\Newextarrow","Not supported",""  },
  {"\\newline","aba\\newline bab","a\\newline b"  },
  {"\\nexists","∄\\nexists∄",""  },
  {"\\ngeq","≱\\ngeq≱",""  },
  {"\\ngeqq","≱\\ngeqq",""  },
  {"\\ngeqslant","≱\\ngeqslant",""  },
  {"\\ngtr","≯\\ngtr≯",""  },
  {"\\ni","∋\\ni∋",""  },
  {"\\nleftarrow","↚\\nleftarrow↚",""  },
  {"\\nLeftarrow","⇍\\nLeftarrow⇍",""  },
  {"\\nLeftrightarrow","⇎\\nLeftrightarrow⇎",""  },
  {"\\nleftrightarrow","↮\\nleftrightarrow↮",""  },
  {"\\nleq","≰\\nleq≰",""  },
  {"\\nleqq","≰\\nleqq",""  },
  {"\\nleqslant","≰\\nleqslant",""  },
  {"\\nless","≮\\nless≮",""  },
  {"\\nmid","∤\\nmid∤",""  },
  {"\\nobreak","",""  },
  {"\\nobreakspace","a ba\\nobreakspace ba b","a\\nobreakspace b"  },
  {"\\noexpand","",""  },
  {"\\nolimits","lim⁡x\\lim\\nolimits_xlimx​","\\lim\\nolimits_x"  },
  {"\\nonumber","a=b+cd+e=f\\begin{align}a&=b+c\\nonumber\\\\d+e&=f\\end{align}ad+e​=b+c=f​​","\\begin{align}\n   a&=b+c \\nonumber\\\\\n   d+e&=f\n\\end{align}"  },
  {"\\normalfont","Not supported",""  },
  {"\\normalsize","normalsize\\normalsize normalsizenormalsize","\\normalsize normalsize"  },
  {"\\not","≠\\not ==","\\not ="  },
  {"\\notag","a=b+cd+e=f\\begin{align}a&=b+c\\notag\\\\d+e&=f\\end{align}ad+e​=b+c=f​​","\\begin{align}\n   a&=b+c \\notag\\\\\n   d+e&=f\n\\end{align}"  },
  {"\\notin","∉\\notin∈/",""  },
  {"\\notni","∌\\notni∋",""  },
  {"\\nparallel","∦\\nparallel∦",""  },
  {"\\nprec","⊀\\nprec⊀",""  },
  {"\\npreceq","⋠\\npreceq⋠",""  },
  {"\\nRightarrow","⇏\\nRightarrow⇏",""  },
  {"\\nrightarrow","↛\\nrightarrow↛",""  },
  {"\\nshortmid","∤\\nshortmid",""  },
  {"\\nshortparallel","∦\\nshortparallel",""  },
  {"\\nsim","≁\\nsim≁",""  },
  {"\\nsubseteq","⊈\\nsubseteq⊈",""  },
  {"\\nsubseteqq","⊈\\nsubseteqq",""  },
  {"\\nsucc","⊁\\nsucc⊁",""  },
  {"\\nsucceq","⋡\\nsucceq⋡",""  },
  {"\\nsupseteq","⊉\\nsupseteq⊉",""  },
  {"\\nsupseteqq","⊉\\nsupseteqq",""  },
  {"\\ntriangleleft","⋪\\ntriangleleft⋪",""  },
  {"\\ntrianglelefteq","⋬\\ntrianglelefteq⋬",""  },
  {"\\ntriangleright","⋫\\ntriangleright⋫",""  },
  {"\\ntrianglerighteq","⋭\\ntrianglerighteq⋭",""  },
  {"\\Nu","N\\NuN",""  },
  {"\\nu","ν\\nuν",""  },
  {"\\nVDash","⊯\\nVDash⊯",""  },
  {"\\nVdash","⊮\\nVdash⊮",""  },
  {"\\nvDash","⊭\\nvDash⊭",""  },
  {"\\nvdash","⊬\\nvdash⊬",""  },
  {"\\nwarrow","↖\\nwarrow↖",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\O","Ø\\text{\\O}Ø","\\text{\\O}"  },
  {"\\o","ø\\text{\\o}ø","\\text{\\o}"  },
  {"\\odot","⊙\\odot⊙",""  },
  {"\\OE","Œ\\text{\\OE}Œ","\\text{\\OE}"  },
  {"\\oe","œ\\text{\\oe}œ","\\text{\\oe}"  },
  {"\\officialeuro","Not supported",""  },
  {"\\oiiint","∰\\oiiint∭​",""  },
  {"\\oiint","∯\\oiint∬​",""  },
  {"\\oint","∮\\oint∮",""  },
  {"\\oldstyle","Not supported",""  },
  {"\\omega","ω\\omegaω",""  },
  {"\\Omega","Ω\\OmegaΩ",""  },
  {"\\Omicron","O\\OmicronO",""  },
  {"\\omicron","ο\\omicronο",""  },
  {"\\ominus","⊖\\ominus⊖",""  },
  {"\\operatorname","asin⁡x\\operatorname{asin} xasinx","\\operatorname{asin} x"  },
  {"\\operatorname*","asin⁡yx\\operatorname*{asin}\\limits_y xyasin​x","\\operatorname*{asin}\\limits_y x"  },
  {"\\operatornamewithlimits","asin⁡yx\\operatornamewithlimits{asin}\\limits_y xyasin​x","\\operatornamewithlimits{asin}\\limits_y x"  },
  {"\\oplus","⊕\\oplus⊕",""  },
  {"\\or","Not supported",""  },
  {"\\origof","⊶\\origof⊶",""  },
  {"\\oslash","⊘\\oslash⊘",""  },
  {"\\otimes","⊗\\otimes⊗",""  },
  {"\\over","a+1b+2+c{a+1 \\over b+2}+cb+2a+1​+c","{a+1 \\over b+2}+c"  },
  {"\\overbrace","x+⋯+x⏞n times\\overbrace{x+⋯+x}^{n\\text{ times}}x+⋯+x​n times​","\\overbrace{x+⋯+x}^{n\\text{ times}}"  },
  {"\\overbracket","Not supported",""  },
  {"\\overgroup","AB⏠\\overgroup{AB}AB","\\overgroup{AB}"  },
  {"\\overleftarrow","AB←\\overleftarrow{AB}AB","\\overleftarrow{AB}"  },
  {"\\overleftharpoon","AB↼\\overleftharpoon{AB}AB","\\overleftharpoon{AB}"  },
  {"\\overleftrightarrow","AB↔\\overleftrightarrow{AB}AB","\\overleftrightarrow{AB}"  },
  {"\\overline","a long argument‾\\overline{\\text{a long argument}}a long argument​","\\overline{\\text{a long argument}}"  },
  {"\\overlinesegment","ABundefined\\overlinesegment{AB}AB","\\overlinesegment{AB}"  },
  {"\\overparen","Not supported","See \\overgroup"  },
  {"\\Overrightarrow","AB⇒\\Overrightarrow{AB}AB","\\Overrightarrow{AB}"  },
  {"\\overrightarrow","AB→\\overrightarrow{AB}AB","\\overrightarrow{AB}"  },
  {"\\overrightharpoon","ac⇀\\overrightharpoon{ac}ac","\\overrightharpoon{ac}"  },
  {"\\overset","=!\\overset{!}{=}=!","\\overset{!}{=}"  },
  {"\\overwithdelims","Not supported",""  },
  {"\\owns","∋\\owns∋",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\P","¶\\text{\\P}¶","\\text{\\P}"  },
  {"\\pagecolor","Not supported","Deprecated"  },
  {"\\parallel","∥\\parallel∥",""  },
  {"\\part","Not supported","Deprecated"  },
  {"\\partial","∂\\partial∂",""  },
  {"\\perp","⊥\\perp⊥",""  },
  {"\\phantom","Γijkij\\Gamma^{\\phantom{i}j}_{i\\phantom{j}k}Γijkij​","\\Gamma^{\\phantom{i}j}_{i\\phantom{j}k}"  },
  {"\\phase","−78∘\\phase{-78^\\circ}−78∘​","\\phase{-78^\\circ}"  },
  {"\\Phi","Φ\\PhiΦ",""  },
  {"\\phi","ϕ\\phiϕ",""  },
  {"\\Pi","Π\\PiΠ",""  },
  {"\\pi","π\\piπ",""  },
  {"{picture}","Not supported",""  },
  {"\\pitchfork","⋔\\pitchfork⋔",""  },
  {"\\plim","plim⁡\\plimplim",""  },
  {"\\plusmn","±\\plusmn±",""  },
  {"\\pm","±\\pm±",""  },
  {"\\pmatrix","Not supported","See {pmatrix}"  },
  {"{pmatrix}","(abcd)\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}(ac​bd​)","\\begin{pmatrix}\n   a & b \\\\\n   c & d\n\\end{pmatrix}"  },
  {"{pmatrix*}","(0−1−10)\\begin{pmatrix*}{r}0&-1\\\\-1&0\\end{pmatrix*}(0−1​−10​)","\\begin{pmatrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{pmatrix*}"  },
  {"\\pmb","μ\\pmb{\\mu}μ","\\pmb{\\mu}"  },
  {"\\pmod","x(moda)x\\pmod ax(moda)","x\\pmod a"  },
  {"\\pod","x(a)x \\pod ax(a)","x \\pod a"  },
  {"\\pounds","£\\pounds£",""  },
  {"\\Pr","Pr⁡\\PrPr",""  },
  {"\\prec","≺\\prec≺",""  },
  {"\\precapprox","⪷\\precapprox⪷",""  },
  {"\\preccurlyeq","≼\\preccurlyeq≼",""  },
  {"\\preceq","⪯\\preceq⪯",""  },
  {"\\precnapprox","⪹\\precnapprox⪹",""  },
  {"\\precneqq","⪵\\precneqq⪵",""  },
  {"\\precnsim","⋨\\precnsim⋨",""  },
  {"\\precsim","≾\\precsim≾",""  },
  {"\\prime","′\\prime′",""  },
  {"\\prod","∏\\prod∏",""  },
  {"\\projlim","proj lim⁡\\projlimprojlim","\\projlim"  },
  {"\\propto","∝\\propto∝",""  },
  {"\\providecommand","Hello\\providecommand\\greet{\\text{Hello}} \\greetHello","\\providecommand\\greet{\\text{Hello}} \\greet"  },
  {"\\psi","ψ\\psiψ",""  },
  {"\\Psi","Ψ\\PsiΨ",""  },
  {"\\pu","123 kJmol{123~\\mathchoice{\\textstyle\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}{\\frac{\\mathrm{kJ}}{\\mathrm{mol}}}}123 molkJ​","\\pu{123 kJ//mol} Requires an extension"  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\Q","Not supported","See \\Bbb{Q}"  },
  {"\\qquad","aba\\qquad\\qquad{b}ab","a\\qquad\\qquad{b}"  },
  {"\\quad","aba\\quad\\quad{b}ab","a\\quad\\quad{b}"  },
  {"\\R","R\\RR",""  },
  {"\\r","a˚\\text{\\r{a}}a˚","\\text{\\r{a}}"  },
  {"\\raise","Not supported","see \\raisebox"  },
  {"\\raisebox","higherh\\raisebox{2pt}{ighe}rhigher","h\\raisebox{2pt}{$ighe$}r"  },
  {"\\rang","⟨A⟩\\langle A\\rang⟨A⟩","\\langle A\\rang"  },
  {"\\rangle","⟨A⟩\\langle A\\rangle⟨A⟩","\\langle A\\rangle"  },
  {"\\Rarr","⇒\\Rarr⇒",""  },
  {"\\rArr","⇒\\rArr⇒",""  },
  {"\\rarr","→\\rarr→",""  },
  {"\\ratio",":\\ratio:",""  },
  {"\\rBrace","⦄\\rBrace}}",""  },
  {"\\rbrace","}\\rbrace}",""  },
  {"\\rbrack","}\\rbrack}",""  },
  {"{rcases}","aif bcif d}\\begin{rcases}a&\\text{if }b\\\\c&\\text{if }d\\end{rcases}ac​if bif d​}","\\begin{rcases}\n   a &\\text{if } b \\\\\n   c &\\text{if } d\n\\end{rcases}"  },
  {"\\rceil","⌉\\rceil⌉",""  },
  {"\\Re","ℜ\\Reℜ",""  },
  {"\\real","ℜ\\realℜ",""  },
  {"\\Reals","R\\RealsR",""  },
  {"\\reals","R\\realsR",""  },
  {"\\ref","Not supported","Issue #350"  },
  {"\\relax","",""  },
  {"\\renewcommand","Ahoy!\\def\\hail{Hi!}\\renewcommand\\hail{\\text{Ahoy!}} \\hailAhoy!","\\def\\hail{Hi!}\n\\renewcommand\\hail{\\text{Ahoy!}}\n\\hail"  },
  {"\\renewenvironment","Not supported",""  },
  {"\\require","Not supported",""  },
  {"\\restriction","↾\\restriction↾",""  },
  {"\\rfloor","⌋\\rfloor⌋",""  },
  {"\\rgroup","⟯\\rgroup⟯",""  },
  {"\\rhd","⊳\\rhd⊳",""  },
  {"\\Rho","P\\RhoP",""  },
  {"\\rho","ρ\\rhoρ",""  },
  {"\\right","ab)\\left.\\dfrac a b\\right)ba​)","\\left.\\dfrac a b\\right)"  },
  {"\\Rightarrow","⇒\\Rightarrow⇒",""  },
  {"\\rightarrow","→\\rightarrow→",""  },
  {"\\rightarrowtail","↣\\rightarrowtail↣",""  },
  {"\\rightharpoondown","⇁\\rightharpoondown⇁",""  },
  {"\\rightharpoonup","⇀\\rightharpoonup⇀",""  },
  {"\\rightleftarrows","⇄\\rightleftarrows⇄",""  },
  {"\\rightleftharpoons","⇌\\rightleftharpoons⇌",""  },
  {"\\rightrightarrows","⇉\\rightrightarrows⇉",""  },
  {"\\rightsquigarrow","⇝\\rightsquigarrow⇝",""  },
  {"\\rightthreetimes","⋌\\rightthreetimes⋌",""  },
  {"\\risingdotseq","≓\\risingdotseq≓",""  },
  {"\\rlap","/=\\rlap{\\,/}{=}/=","\\rlap{\\,/}{=}"  },
  {"\\rm","AaBb12\\rm AaBb12AaBb12","\\rm AaBb12"  },
  {"\\rmoustache","⎱\\rmoustache⎱",""  },
  {"\\root","Not supported",""  },
  {"\\rotatebox","Not supported","Issue #681"  },
  {"\\rparen",")\\rparen)",""  },
  {"\\rq","′\\rq′",""  },
  {"\\rrbracket","⟧\\rrbracket}}",""  },
  {"\\Rrightarrow","⇛\\Rrightarrow⇛",""  },
  {"\\Rsh","↱\\Rsh↱",""  },
  {"\\rtimes","⋊\\rtimes⋊",""  },
  {"\\Rule","Not supported","see \\rule"  },
  {"\\rule","xxx\\rule{6pt}{2ex}{1ex}xxx","x\\rule{6pt}{2ex}{1ex}x"  },
  {"\\rVert","∥\\rVert∥",""  },
  {"\\rvert","∣\\rvert∣",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\S","§\\text{\\S}§","\\text{\\S}"  },
  {"\\Sampi","Not supported",""  },
  {"\\sampi","Not supported",""  },
  {"\\sc","Not supported","Issue #471"  },
  {"\\scalebox","Not supported",""  },
  {"\\scr","Not supported","See \\mathscr"  },
  {"\\scriptscriptstyle","cd\\scriptscriptstyle \\frac cddc​","\\scriptscriptstyle \\frac cd"  },
  {"\\scriptsize","scriptsize\\scriptsize scriptsizescriptsize","\\scriptsize scriptsize"  },
  {"\\scriptstyle","ab+cd\\frac ab + {\\scriptstyle \\frac cd}ba​+dc​","\\frac ab + {\\scriptstyle \\frac cd}"  },
  {"\\sdot","? \\sdot?",""  },
  {"\\searrow","↘\\searrow↘",""  },
  {"\\sec","sec⁡\\secsec",""  },
  {"\\sect","§\\text{\\sect}§","\\text{\\sect}"  },
  {"\\set","{ x∣x<5 }\\set{x\\VERT x<5}{x∣x<5}","\\set{x|x<5}"  },
  {"\\Set","{? x?  |?  x<12? }\\Set{ x \\VERT x<\\frac 1 2 }{x​x<21​}","\\Set{ x | x<\\frac 1 2}"  },
  {"\\setlength","Not supported","Issue #687"  },
  {"\\setminus","∖\\setminus∖",""  },
  {"\\sf","AaBb123\\sf AaBb123AaBb123","\\sf AaBb123"  },
  {"\\sharp","♯\\sharp♯",""  },
  {"\\shortmid","∣\\shortmid∣",""  },
  {"\\shortparallel","∥\\shortparallel∥",""  },
  {"\\shoveleft","Not supported",""  },
  {"\\shoveright","Not supported",""  },
  {"\\sideset","Not supported",""  },
  {"\\Sigma","Σ\\SigmaΣ",""  },
  {"\\sigma","σ\\sigmaσ",""  },
  {"\\sim","∼\\sim∼",""  },
  {"\\simcolon","∼:\\simcolon∼:",""  },
  {"\\simcoloncolon","∼∷\\simcoloncolon∼::",""  },
  {"\\simeq","≃\\simeq≃",""  },
  {"\\sin","sin⁡\\sinsin",""  },
  {"\\sinh","sinh⁡\\sinhsinh",""  },
  {"\\sixptsize","sixptsize\\sixptsize sixptsizesixptsize","\\sixptsize sixptsize"  },
  {"\\sh","sh⁡\\shsh",""  },
  {"\\skew","Not supported",""  },
  {"\\skip","Not supported",""  },
  {"\\sl","Not supported",""  },
  {"\\small","small\\small smallsmall","\\small small"  },
  {"\\smallfrown","⌢\\smallfrown⌢",""  },
  {"\\smallint","∫\\smallint∫",""  },
  {"{smallmatrix}","abcd\\begin{smallmatrix} a & b \\\\ c & d \\end{smallmatrix}ac​bd​","\\begin{smallmatrix}\n   a & b \\\\\n   c & d\n\\end{smallmatrix}"  },
  {"\\smallsetminus","∖\\smallsetminus∖",""  },
  {"\\smallsmile","⌣\\smallsmile⌣",""  },
  {"\\smash","(x2)\\left(x^{\\smash{2}}\\right)(x2)","\\left(x^{\\smash{2}}\\right)"  },
  {"\\smile","⌣\\smile⌣",""  },
  {"\\smiley","Not supported",""  },
  {"\\sout","abc\\sout{abc}abc","\\sout{abc}"  },
  {"\\Space","Not supported","see \\space"  },
  {"\\space","a ba\\space ba b","a\\space b"  },
  {"\\spades","♠\\spades♠",""  },
  {"\\spadesuit","♠\\spadesuit♠",""  },
  {"\\sphericalangle","∢\\sphericalangle∢",""  },
  {"{split}","a=b+c=e+f\\begin{equation}\\begin{split}a &=b+c\\\\&=e+f\\end{split}\\end{equation}a​=b+c=e+f​​​","\\begin{equation}\n\\begin{split}\n   a &=b+c\\\\\n      &=e+f\n\\end{split}\n\\end{equation}"  },
  {"\\sqcap","⊓\\sqcap⊓",""  },
  {"\\sqcup","⊔\\sqcup⊔",""  },
  {"\\square","□\\square□",""  },
  {"\\sqrt","x3\\sqrt{3}{x}3x​","\\sqrt{3}{x}"  },
  {"\\sqsubset","⊏\\sqsubset⊏",""  },
  {"\\sqsubseteq","⊑\\sqsubseteq⊑",""  },
  {"\\sqsupset","⊐\\sqsupset⊐",""  },
  {"\\sqsupseteq","⊒\\sqsupseteq⊒",""  },
  {"\\ss","ß\\text{\\ss}ß","\\text{\\ss}"  },
  {"\\stackrel","=!\\stackrel{!}{=}=!","\\stackrel{!}{=}"  },
  {"\\star","⋆\\star⋆",""  },
  {"\\Stigma","Not supported",""  },
  {"\\stigma","Not supported",""  },
  {"\\strut","Not supported",""  },
  {"\\style","Not supported","Non standard"  },
  {"\\sub","⊂\\sub⊂",""  },
  {"{subarray}","Not supported",""  },
  {"\\sube","⊆\\sube⊆",""  },
  {"\\Subset","⋐\\Subset⋐",""  },
  {"\\subset","⊂\\subset⊂",""  },
  {"\\subseteq","⊆\\subseteq⊆",""  },
  {"\\subseteqq","? \\subseteqq?",""  },
  {"\\subsetneq","⊊\\subsetneq⊊",""  },
  {"\\subsetneqq","⫋\\subsetneqq⫋",""  },
  {"\\substack","∑0<i<m0<j<n\\sum_{\\substack{0<i<m\\\\0<j<n}}0<i<m0<j<n​∑​","\\sum_{\\substack{0<i<m\\\\0<j<n}}"  },
  {"\\succ","≻\\succ≻",""  },
  {"\\succapprox","⪸\\succapprox⪸",""  },
  {"\\succcurlyeq","≽\\succcurlyeq≽",""  },
  {"\\succeq","⪰\\succeq⪰",""  },
  {"\\succnapprox","⪺\\succnapprox⪺",""  },
  {"\\succneqq","⪶\\succneqq⪶",""  },
  {"\\succnsim","⋩\\succnsim⋩",""  },
  {"\\succsim","≿\\succsim≿",""  },
  {"\\sum","∑\\sum∑",""  },
  {"\\sup","sup⁡\\supsup",""  },
  {"\\supe","⊇\\supe⊇",""  },
  {"\\Supset","⋑\\Supset⋑",""  },
  {"\\supset","⊃\\supset⊃",""  },
  {"\\supseteq","⊇\\supseteq⊇",""  },
  {"\\supseteqq","⫆\\supseteqq⫆",""  },
  {"\\supsetneq","⊋\\supsetneq⊋",""  },
  {"\\supsetneqq","⫌\\supsetneqq⫌",""  },
  {"\\surd","√\\surd√",""  },
  {"\\swarrow","↙\\swarrow↙",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\tag","a2+b2=c2(3.1c)\\tag{3.1c} a^2+b^2=c^2a2+b2=c2(3.1c)","\\tag{3.1c} a^2+b^2=c^2"  },
  {"\\tag*","a2+b2=c23.1c\\tag*{3.1c} a^2+b^2=c^2a2+b2=c23.1c","\\tag*{3.1c} a^2+b^2=c^2"  },
  {"\\tan","tan⁡\\tantan",""  },
  {"\\tanh","tanh⁡\\tanhtanh",""  },
  {"\\Tau","T\\TauT",""  },
  {"\\tau","τ\\tauτ",""  },
  {"\\tbinom","(nk)\\tbinom n k(kn​)","\\tbinom n k"  },
  {"\\TeX","TeX\\TeXTE​X",""  },
  {"\\text","yes & no \\text{ yes }\\&\\text{ no } yes & no","\\text{ yes }\\&\\text{ no }"  },
  {"\\textasciitilde","~\\text{\\textasciitilde}~","\\text{\\textasciitilde}"  },
  {"\\textasciicircum","^\\text{\\textasciicircum}^","\\text{\\textasciicircum}"  },
  {"\\textbackslash","\\\\text{\\textbackslash}\\","\\text{\\textbackslash}"  },
  {"\\textbar","|\\text{\\textbar}|","\\text{\\textbar}"  },
  {"\\textbardbl","∥\\text{\\textbardbl}∥","\\text{\\textbardbl}"  },
  {"\\textbf","AaBb123\\textbf{AaBb123}AaBb123","\\textbf{AaBb123}"  },
  {"\\textbraceleft","{\\text{\\textbraceleft}{","\\text{\\textbraceleft}"  },
  {"\\textbraceright","}\\text{\\textbraceright}}","\\text{\\textbraceright}"  },
  {"\\textcircled","a◯\\text{\\textcircled a}a◯","\\text{\\textcircled a}"  },
  {"\\textcolor","F=ma\\textcolor{blue}{F=ma}F=ma","\\textcolor{blue}{F=ma}"  },
  {"\\textdagger","†\\text{\\textdagger}†","\\text{\\textdagger}"  },
  {"\\textdaggerdbl","‡\\text{\\textdaggerdbl}‡","\\text{\\textdaggerdbl}"  },
  {"\\textdegree","°\\text{\\textdegree}°","\\text{\\textdegree}"  },
  {"\\textdollar","$\\text{\\textdollar}$","\\text{\\textdollar}"  },
  {"\\textellipsis","…\\text{\\textellipsis}…","\\text{\\textellipsis}"  },
  {"\\textemdash","—\\text{\\textemdash}—","\\text{\\textemdash}"  },
  {"\\textendash","–\\text{\\textendash}–","\\text{\\textendash}"  },
  {"\\textgreater",">\\text{\\textgreater}>","\\text{\\textgreater}"  },
  {"\\textit","AaBb\\textit{AaBb}AaBb","\\textit{AaBb}"  },
  {"\\textless","<\\text{\\textless}<","\\text{\\textless}"  },
  {"\\textmd","AaBb123\\textmd{AaBb123}AaBb123","\\textmd{AaBb123}"  },
  {"\\textnormal","AB\\textnormal{AB}AB","\\textnormal{AB}"  },
  {"\\textquotedblleft","“\\text{\\textquotedblleft}“","\\text{\\textquotedblleft}"  },
  {"\\textquotedblright","”\\text{\\textquotedblright}”","\\text{\\textquotedblright}"  },
  {"\\textquoteleft","‘\\text{\\textquoteleft}‘","\\text{\\textquoteleft}"  },
  {"\\textquoteright","’\\text{\\textquoteright}’","\\text{\\textquoteright}"  },
  {"\\textregistered","®\\text{\\textregistered}R◯","\\text{\\textregistered}"  },
  {"\\textrm","AaBb123\\textrm{AaBb123}AaBb123","\\textrm{AaBb123}"  },
  {"\\textsc","Not supported","Issue #471"  },
  {"\\textsf","AaBb123\\textsf{AaBb123}AaBb123","\\textsf{AaBb123}"  },
  {"\\textsl","Not supported",""  },
  {"\\textsterling","£\\text{\\textsterling}£","\\text{\\textsterling}"  },
  {"\\textstyle","∑0n\\textstyle\\sum_0^n∑0n​","\\textstyle\\sum_0^n"  },
  {"\\texttip","Not supported",""  },
  {"\\texttt","AaBb123\\texttt{AaBb123}AaBb123","\\texttt{AaBb123}"  },
  {"\\textunderscore","_\\text{\\textunderscore}_","\\text{\\textunderscore}"  },
  {"\\textup","AaBb123\\textup{AaBb123}AaBb123","\\textup{AaBb123}"  },
  {"\\textvisiblespace","Not supported",""  },
  {"\\tfrac","ab\\tfrac abba​","\\tfrac ab"  },
  {"\\tg","tg⁡\\tgtg",""  },
  {"\\th","th⁡\\thth",""  },
  {"\\therefore","∴\\therefore∴",""  },
  {"\\Theta","Θ\\ThetaΘ",""  },
  {"\\theta","θ\\thetaθ",""  },
  {"\\thetasym","ϑ\\thetasymϑ",""  },
  {"\\thickapprox","≈\\thickapprox≈",""  },
  {"\\thicksim","∼\\thicksim∼",""  },
  {"\\thickspace","a?  ba\\thickspace bab","a\\thickspace b"  },
  {"\\thinspace","a ba\\thinspace bab","a\\thinspace b"  },
  {"\\tilde","M~\\tilde MM~","\\tilde M"  },
  {"\\times","×\\times×",""  },
  {"\\Tiny","Not supported","see \\tiny"  },
  {"\\tiny","tiny\\tiny tinytiny","\\tiny tiny"  },
  {"\\to","→\\to→",""  },
  {"\\toggle","Not supported",""  },
  {"\\top","⊤\\top⊤",""  },
  {"\\triangle","△\\triangle△",""  },
  {"\\triangledown","▽\\triangledown▽",""  },
  {"\\triangleleft","◃\\triangleleft◃",""  },
  {"\\trianglelefteq","⊴\\trianglelefteq⊴",""  },
  {"\\triangleq","≜\\triangleq≜",""  },
  {"\\triangleright","▹\\triangleright▹",""  },
  {"\\trianglerighteq","⊵\\trianglerighteq⊵",""  },
  {"\\tt","AaBb123{\\tt AaBb123}AaBb123","{\\tt AaBb123}"  },
  {"\\twoheadleftarrow","↞\\twoheadleftarrow↞",""  },
  {"\\twoheadrightarrow","↠\\twoheadrightarrow↠",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\u","a˘\\text{\\u{a}}a˘","\\text{\\u{a}}"  },
  {"\\Uarr","⇑\\Uarr⇑",""  },
  {"\\uArr","⇑\\uArr⇑",""  },
  {"\\uarr","↑\\uarr↑",""  },
  {"\\ulcorner","⌜\\ulcorner┌",""  },
  {"\\underbar","X‾\\underbar{X}X​","\\underbar{X}"  },
  {"\\underbrace","x+⋯+x⏟n times\\underbrace{x+⋯+x}_{n\\text{ times}}n timesx+⋯+x​​","\\underbrace{x+⋯+x}_{n\\text{ times}}"  },
  {"\\underbracket","Not supported",""  },
  {"\\undergroup","AB⏡\\undergroup{AB}AB​","\\undergroup{AB}"  },
  {"\\underleftarrow","AB←\\underleftarrow{AB}AB​","\\underleftarrow{AB}"  },
  {"\\underleftrightarrow","AB↔\\underleftrightarrow{AB}AB​","\\underleftrightarrow{AB}"  },
  {"\\underrightarrow","AB→\\underrightarrow{AB}AB​","\\underrightarrow{AB}"  },
  {"\\underline","a long argument‾\\underline{\\text{a long argument}}a long argument​","\\underline{\\text{a long argument}}"  },
  {"\\underlinesegment","ABundefined\\underlinesegment{AB}AB​","\\underlinesegment{AB}"  },
  {"\\underparen","Not supported","See \\undergroup"  },
  {"\\underrightarrow","AB→\\underrightarrow{AB}AB​","\\underrightarrow{AB}"  },
  {"\\underset","=!\\underset{!}{=}!=​","\\underset{!}{=}"  },
  {"\\unicode","Not supported",""  },
  {"\\unlhd","⊴\\unlhd⊴",""  },
  {"\\unrhd","⊵\\unrhd⊵",""  },
  {"\\up","Not supported",""  },
  {"\\Uparrow","⇑\\Uparrow⇑",""  },
  {"\\uparrow","↑\\uparrow↑",""  },
  {"\\Updownarrow","⇕\\Updownarrow⇕",""  },
  {"\\updownarrow","↕\\updownarrow↕",""  },
  {"\\upharpoonleft","↿\\upharpoonleft↿",""  },
  {"\\upharpoonright","↾\\upharpoonright↾",""  },
  {"\\uplus","⊎\\uplus⊎",""  },
  {"\\uproot","Not supported",""  },
  {"\\upshape","Not supported",""  },
  {"\\Upsilon","Υ\\UpsilonΥ",""  },
  {"\\upsilon","? \\upsilon?",""  },
  {"\\upuparrows","⇈\\upuparrows⇈",""  },
  {"\\urcorner","⌝\\urcorner┐",""  },
  {"\\url","https://katex.org/\\footnotesize\\url{https://katex.org/}https://katex.org/","\\url{https://katex.org/} Requires trust option"  },
  {"\\utilde","AB~\\utilde{AB}AB​","\\utilde{AB}"  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\v","aˇ\\text{\\v{a}}aˇ","\\text{\\v{a}}"  },
  {"\\varcoppa","Not supported",""  },
  {"\\varDelta","Δ\\varDeltaΔ",""  },
  {"\\varepsilon","ε\\varepsilonε",""  },
  {"\\varGamma","Γ\\varGammaΓ",""  },
  {"\\varinjlim","lim→⁡\\varinjlimlim​","\\varinjlim"  },
  {"\\varkappa","ϰ\\varkappaϰ",""  },
  {"\\varLambda","Λ\\varLambdaΛ",""  },
  {"\\varliminf","lim‾⁡\\varliminflim​","\\varliminf"  },
  {"\\varlimsup","lim‾⁡\\varlimsuplim","\\varlimsup"  },
  {"\\varnothing","? \\varnothing?",""  },
  {"\\varOmega","Ω\\varOmegaΩ",""  },
  {"\\varPhi","Φ\\varPhiΦ",""  },
  {"\\varphi","φ\\varphiφ",""  },
  {"\\varPi","Π\\varPiΠ",""  },
  {"\\varpi","ϖ\\varpiϖ",""  },
  {"\\varprojlim","lim←⁡\\varprojlimlim​","\\varprojlim"  },
  {"\\varpropto","∝\\varpropto∝",""  },
  {"\\varPsi","Ψ\\varPsiΨ",""  },
  {"\\varrho","ϱ\\varrhoϱ",""  },
  {"\\varSigma","Σ\\varSigmaΣ",""  },
  {"\\varsigma","ς\\varsigmaς",""  },
  {"\\varstigma","Not supported",""  },
  {"\\varsubsetneq","⊊\\varsubsetneq",""  },
  {"\\varsubsetneqq","⫋\\varsubsetneqq",""  },
  {"\\varsupsetneq","⊋\\varsupsetneq",""  },
  {"\\varsupsetneqq","⫌\\varsupsetneqq",""  },
  {"\\varTheta","Θ\\varThetaΘ",""  },
  {"\\vartheta","ϑ\\varthetaϑ",""  },
  {"\\vartriangle","△\\vartriangle△",""  },
  {"\\vartriangleleft","⊲\\vartriangleleft⊲",""  },
  {"\\vartriangleright","⊳\\vartriangleright⊳",""  },
  {"\\varUpsilon","Υ\\varUpsilonΥ",""  },
  {"\\varXi","Ξ\\varXiΞ",""  },
  {"\\vcentcolon",":=\\mathrel{\\vcentcolon =}:=","\\mathrel{\\vcentcolon =}"  },
  {"\\vcenter","a+(abc)a+\\left(\\vcenter{\\frac{\\frac a b}c}\\right)a+(cba​​​)","a+\\left(\\vcenter{\\hbox{$\\frac{\\frac a b}c$}}\\right)\nTeX (strict) syntax"  },
  {"\\vcenter","a+(abc)a+\\left(\\vcenter{\\frac{\\frac a b}c}\\right)a+(cba​​​)","a+\\left(\\vcenter{\\frac{\\frac a b}c}\\right)\nnon-strict syntax"  },
  {"\\Vdash","⊩\\Vdash⊩",""  },
  {"\\vDash","⊨\\vDash⊨",""  },
  {"\\vdash","⊢\\vdash⊢",""  },
  {"\\vdots","⋮\\vdots⋮",""  },
  {"\\vec","F⃗\\vec{F}F","\\vec{F}"  },
  {"\\vee","∨\\vee∨",""  },
  {"\\veebar","⊻\\veebar⊻",""  },
  {"\\verb","\\frac a b\\verb!\\frac a b!\\frac a b","\\verb!\\frac a b!"  },
  {"\\Vert","∥\\Vert∥",""  },
  {"\\vert","∣\\vert∣",""  },
  {"\\vfil","Not supported",""  },
  {"\\vfill","Not supported",""  },
  {"\\vline","Not supported","Issue #269"  },
  {"{Vmatrix}","∥abcd∥\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}​ac​bd​​","\\begin{Vmatrix}\n   a & b \\\\\n   c & d\n\\end{Vmatrix}"  },
  {"{Vmatrix*}","∥0−1−10∥\\begin{Vmatrix*}{r}0&-1\\\\-1&0\\end{Vmatrix*}​0−1​−10​​","\\begin{Vmatrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{Vmatrix*}"  },
  {"{vmatrix}","∣abcd∣\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}​ac​bd​​","\\begin{vmatrix}\n   a & b \\\\\n   c & d\n\\end{vmatrix}"  },
  {"{vmatrix*}","∣0−1−10∣\\begin{vmatrix*}{r}0&-1\\\\-1&0\\end{vmatrix*}​0−1​−10​​","\\begin{vmatrix*}{r}\n   0 & -1 \\\\\n   -1 & 0\n\\end{vmatrix*}"  },
  {"\\vphantom","Ma‾\\overline{\\vphantom{M}a}Ma","\\overline{\\vphantom{M}a}"  },
  {"\\Vvdash","⊪\\Vvdash⊪",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\wedge","∧\\wedge∧",""  },
  {"\\weierp","℘\\weierp℘",""  },
  {"\\widecheck","ABˇ\\widecheck{AB}AB","\\widecheck{AB}"  },
  {"\\widehat","AB^\\widehat{AB}AB","\\widehat{AB}"  },
  {"\\wideparen","Not supported","Issue #560"  },
  {"\\widetilde","AB~\\widetilde{AB}AB","\\widetilde{AB}"  },
  {"\\wp","℘\\wp℘",""  },
  {"\\wr","≀\\wr≀",""  },
  {"Symbol/Function","Rendered","Source or Comment"  },
  {"\\xcancel","ABC\\xcancel{ABC}ABC","\\xcancel{ABC}"  },
  {"\\xdef","a\\def\\foo{a}\\xdef\\fcopy{\\foo}\\def\\foo{}\\fcopya","\\def\\foo{a}\\xdef\\fcopy{\\foo}\\def\\foo{}\\fcopy"  },
  {"\\Xi","Ξ\\XiΞ",""  },
  {"\\xi","ξ\\xiξ",""  },
  {"\\xhookleftarrow","↩abc\\xhookleftarrow{abc}abc​","\\xhookleftarrow{abc}"  },
  {"\\xhookrightarrow","↪abc\\xhookrightarrow{abc}abc​","\\xhookrightarrow{abc}"  },
  {"\\xLeftarrow","⇐abc\\xLeftarrow{abc}abc​","\\xLeftarrow{abc}"  },
  {"\\xleftarrow","←abc\\xleftarrow{abc}abc​","\\xleftarrow{abc}"  },
  {"\\xleftharpoondown","↽abc\\xleftharpoondown{abc}abc​","\\xleftharpoondown{abc}"  },
  {"\\xleftharpoonup","↼abc\\xleftharpoonup{abc}abc​","\\xleftharpoonup{abc}"  },
  {"\\xLeftrightarrow","⇔abc\\xLeftrightarrow{abc}abc​","\\xLeftrightarrow{abc}"  },
  {"\\xleftrightarrow","↔abc\\xleftrightarrow{abc}abc​","\\xleftrightarrow{abc}"  },
  {"\\xleftrightharpoons","⇋abc\\xleftrightharpoons{abc}abc​","\\xleftrightharpoons{abc}"  },
  {"\\xlongequal","=abc\\xlongequal{abc}abc","\\xlongequal{abc}"  },
  {"\\xmapsto","↦abc\\xmapsto{abc}abc​","\\xmapsto{abc}"  },
  {"\\xRightarrow","⇒abc\\xRightarrow{abc}abc​","\\xRightarrow{abc}"  },
  {"\\xrightarrow","→abc\\xrightarrow{abc}abc​","\\xrightarrow{abc}"  },
  {"\\xrightharpoondown","⇁abc\\xrightharpoondown{abc}abc​","\\xrightharpoondown{abc}"  },
  {"\\xrightharpoonup","⇀abc\\xrightharpoonup{abc}abc​","\\xrightharpoonup{abc}"  },
  {"\\xrightleftharpoons","⇌abc\\xrightleftharpoons{abc}abc​","\\xrightleftharpoons{abc}"  },
  {"\\xtofrom","⇄abc\\xtofrom{abc}abc​","\\xtofrom{abc}"  },
  {"\\xtwoheadleftarrow","↞abc\\xtwoheadleftarrow{abc}abc","\\xtwoheadleftarrow{abc}"  },
  {"\\xtwoheadrightarrow","↠abc\\xtwoheadrightarrow{abc}abc","\\xtwoheadrightarrow{abc}"  },
  {"\\yen","¥\\yen¥",""  },
  {"\\Z","Z\\ZZ",""  },
  {"\\Zeta","Z\\ZetaZ",""  },
  {"\\zeta","ζ\\zetaζ",""  },
}
